region: <your-aws-region>

iam_user_arn: <your-iam-user-arn> # ARN running this template (your user)
database_name: ragvectordatabase
knowledge_base_name: rag-kb

embeddings_model_id: amazon.titan-embed-text-v1
chat_model_id: anthropic.claude-3-haiku-20240307-v1:0
#chat_model_id: anthropic.claude-3-sonnet-20240229-v1:0

chunking_strategy: HIERARCHICAL
# Hierarchical configuration
hierarchical:
  overlap_tokens: 20
  max_parent_tokens: 1500
  max_child_tokens: 300

# Fixed size configuration
fixed_size:
  max_tokens: 300
  overlap_percentage: 20

# Semantic configuration
semantic:
  max_tokens: 300
  breakpoint_percentile_threshold: 90
  buffer_size: 0

bot_name: publichealthbot
